namespace MythosGraph.Domain.Enums;

public enum RelationType
{
    AppearsIn = 1,
    BelongsToTradition = 2,
    OriginatesFrom = 3,
    Inhabits = 4,
    HasDomain = 5,
    Wields = 6,
    CreatedBy = 7,
    ParentOf = 8,
    ChildOf = 9,
    SiblingOf = 10,
    RivalOf = 11,
    EnemyOf = 12,
    AllyOf = 13,
    SlainBy = 14,
    Slays = 15,
    Guards = 16,
    AssociatedWith = 17,
    SimilarTo = 18,
    InspiredBy = 19,
    HasWeakness = 20,
    CounteredBy = 21,
    RequiresRitual = 22,
    LocatedIn = 23,
    SpouseOf = 24,
    RomanEquivalentOf = 25,
    PrecedesInCosmogony = 26,
    ConsortOf = 27,
    CastratedBy = 28,
    ImprisonedIn = 29,
    RulesOver = 30,
    Castrates = 31,
    OverthrownBy = 32
}
